# Generated by Django 2.1.7 on 2019-10-06 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=32, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('createddate', models.DateField(blank=True, db_column='CreatedDate', null=True)),
                ('modifieddate', models.DateField(blank=True, db_column='ModifiedDate', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'Backlog',
            },
        ),
        migrations.CreateModel(
            name='BacklogSprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('id_backlog', models.ForeignKey(blank=True, db_column='ID_Backlog', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.Backlog')),
            ],
            options={
                'db_table': 'BacklogSprint',
            },
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=32, null=True)),
                ('summary', models.TextField(blank=True, db_column='Summary', null=True)),
                ('createddate', models.DateField(blank=True, db_column='CreatedDate', null=True)),
                ('modifieddate', models.DateField(blank=True, db_column='ModifiedDate', null=True)),
            ],
            options={
                'db_table': 'Epic',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=32, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('begindate', models.DateField(blank=True, db_column='BeginDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('goal', models.TextField(blank=True, db_column='Goal', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('createddate', models.DateField(blank=True, db_column='CreatedDate', null=True)),
                ('modifieddate', models.DateField(blank=True, db_column='ModifiedDate', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=10, null=True)),
                ('retrospective', models.TextField(blank=True, db_column='Retrospective', null=True)),
            ],
            options={
                'db_table': 'Sprint',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(db_column='Email', max_length=50, primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, db_column='Nama', max_length=50, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=50, null=True)),
                ('role', models.CharField(blank=True, db_column='Role', max_length=20, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Userproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(blank=True, db_column='Email', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.User')),
                ('id_project', models.ForeignKey(blank=True, db_column='ID_Project', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.Project')),
            ],
            options={
                'db_table': 'UserProject',
            },
        ),
        migrations.AddField(
            model_name='sprint',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdbys', to='jectman.User'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='id_project',
            field=models.ForeignKey(blank=True, db_column='ID_Project', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.Project'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='modifiedby',
            field=models.ForeignKey(blank=True, db_column='ModifiedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedbys', to='jectman.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='id_user',
            field=models.ForeignKey(blank=True, db_column='ID_User', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.User'),
        ),
        migrations.AddField(
            model_name='epic',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdbye', to='jectman.User'),
        ),
        migrations.AddField(
            model_name='epic',
            name='id_project',
            field=models.ForeignKey(blank=True, db_column='ID_Project', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.Project'),
        ),
        migrations.AddField(
            model_name='epic',
            name='modifiedby',
            field=models.ForeignKey(blank=True, db_column='ModifiedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedbye', to='jectman.User'),
        ),
        migrations.AddField(
            model_name='backlogsprint',
            name='id_sprint',
            field=models.ForeignKey(blank=True, db_column='ID_Sprint', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.Sprint'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='assignee',
            field=models.ForeignKey(blank=True, db_column='Assignee', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignee', to='jectman.User'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdbyb', to='jectman.User'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='id_epic',
            field=models.ForeignKey(blank=True, db_column='ID_Epic', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.Epic'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='id_project',
            field=models.ForeignKey(blank=True, db_column='ID_Project', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.Project'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='id_sprint',
            field=models.ForeignKey(blank=True, db_column='ID_Sprint', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.Sprint'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='modifiedby',
            field=models.ForeignKey(blank=True, db_column='ModifiedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedbyb', to='jectman.User'),
        ),
    ]
