# Generated by Django 2.1.7 on 2019-09-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jectman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=32, null=True)),
                ('summary', models.TextField(blank=True, db_column='Summary', null=True)),
                ('createddate', models.DateField(blank=True, db_column='CreatedDate', null=True)),
                ('modifieddate', models.DateField(blank=True, db_column='ModifiedDate', null=True)),
            ],
            options={
                'db_table': 'Epic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sprintreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('completedbacklog', models.IntegerField(blank=True, db_column='CompletedBacklog', null=True)),
            ],
            options={
                'db_table': 'SprintReport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(db_column='Email', max_length=50, primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, db_column='Nama', max_length=50, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=50, null=True)),
                ('role', models.CharField(blank=True, db_column='Role', max_length=20, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'UserProject',
                'managed': False,
            },
        ),
    ]
