# Generated by Django 2.1.7 on 2019-10-04 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jectman', '0002_epic_sprintreport_user_userproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogSprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'BacklogSprint',
            },
        ),
        migrations.AlterModelOptions(
            name='backlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='epic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userproject',
            options={},
        ),
        migrations.AddField(
            model_name='backlogsprint',
            name='id_backlog',
            field=models.ForeignKey(blank=True, db_column='ID_Backlog', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.Backlog'),
        ),
        migrations.AddField(
            model_name='backlogsprint',
            name='id_sprint',
            field=models.ForeignKey(blank=True, db_column='ID_Sprint', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.Sprint'),
        ),
    ]
