# Generated by Django 2.1.7 on 2019-09-10 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jectman', '0002_epic_sprintreport_user_userproject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='epic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sprint',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sprintreport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userproject',
            options={},
        ),
    ]
