# Generated by Django 2.1.7 on 2019-09-10 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jectman', '0005_auto_20190910_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=32, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('createddate', models.DateField(blank=True, db_column='CreatedDate', null=True)),
                ('modifieddate', models.DateField(blank=True, db_column='ModifiedDate', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'Backlog',
            },
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=32, null=True)),
                ('summary', models.TextField(blank=True, db_column='Summary', null=True)),
                ('createddate', models.DateField(blank=True, db_column='CreatedDate', null=True)),
                ('modifieddate', models.DateField(blank=True, db_column='ModifiedDate', null=True)),
            ],
            options={
                'db_table': 'Epic',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=32, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('begindate', models.DateField(blank=True, db_column='BeginDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('goal', models.TextField(blank=True, db_column='Goal', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('createddate', models.DateField(blank=True, db_column='CreatedDate', null=True)),
                ('modifieddate', models.DateField(blank=True, db_column='ModifiedDate', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=10, null=True)),
                ('retrospective', models.TextField(blank=True, db_column='Retrospective', null=True)),
            ],
            options={
                'db_table': 'Sprint',
            },
        ),
        migrations.CreateModel(
            name='Sprintreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('completedbacklog', models.IntegerField(blank=True, db_column='CompletedBacklog', null=True)),
                ('id_sprint', models.ForeignKey(blank=True, db_column='ID_Sprint', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.Sprint')),
            ],
            options={
                'db_table': 'SprintReport',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(db_column='Email', max_length=50, primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, db_column='Nama', max_length=50, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=50, null=True)),
                ('role', models.CharField(blank=True, db_column='Role', max_length=20, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Userproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(blank=True, db_column='Email', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.User')),
                ('id_project', models.ForeignKey(blank=True, db_column='ID_Project', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.Project')),
            ],
            options={
                'db_table': 'UserProject',
            },
        ),
        migrations.AddField(
            model_name='sprint',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdbys', to='jectman.User'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='id_project',
            field=models.ForeignKey(blank=True, db_column='ID_Project', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.Project'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='modifiedby',
            field=models.ForeignKey(blank=True, db_column='ModifiedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedbys', to='jectman.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='id_user',
            field=models.ForeignKey(blank=True, db_column='ID_User', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.User'),
        ),
        migrations.AddField(
            model_name='epic',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdbye', to='jectman.User'),
        ),
        migrations.AddField(
            model_name='epic',
            name='id_project',
            field=models.ForeignKey(blank=True, db_column='ID_Project', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.Project'),
        ),
        migrations.AddField(
            model_name='epic',
            name='modifiedby',
            field=models.ForeignKey(blank=True, db_column='ModifiedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedbye', to='jectman.User'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='assignee',
            field=models.ForeignKey(blank=True, db_column='Assignee', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignee', to='jectman.User'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdbyb', to='jectman.User'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='id_epic',
            field=models.ForeignKey(blank=True, db_column='ID_Epic', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.Epic'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='id_project',
            field=models.ForeignKey(blank=True, db_column='ID_Project', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.Project'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='id_sprint',
            field=models.ForeignKey(blank=True, db_column='ID_Sprint', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jectman.Sprint'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='modifiedby',
            field=models.ForeignKey(blank=True, db_column='ModifiedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedbyb', to='jectman.User'),
        ),
    ]
